/*
 ! RECURSION
 ? REQUIREMENTS: KNOWLEDGE OF ITERATION(for, while, do-while loop's) + Function's
 ? RECURSION IS A METHOD OF SOLVING A COMPUTATIONAL PROBLEM WHAERE SOLUTION IS DEPEND ON SOLUTION TO SMALLER INSTANCES OF THE SAME PEROBLEM

 * BEST EXAMPLE IF FACTORIAL PROCESS: 
 * 5!= 5*4! = 5*4*3! = 5*4*3*2! = 5*4*3*2*1! = 120
 */

public class recursion1 {
    
}
